name: gpiojawn
version: '2.1'
summary: A package for blinking an LED
description: |
  Repeatedly blink an LED until Ctrl+C is detected

grade: stable
confinement: strict
base: core20

architectures:
  - build-on: [armhf, arm64]
    run-on: [armhf, arm64]

parts:
  gpiojawn:
    plugin: dump
    source: src/

apps:
  gpiojawn:
    command: bin/gpiojawn.sh
    plugs:
      - gpio
