name: pwmjawn
base: core20
version: '1.0'
summary: Set PWM speeds in /sys/class/ on a Raspberry Pi
description: |
  A snap to directly interface with hardware PWM on a Raspberry Pi. Requires
  setting dtoverlay=pwm-2chan in config.txt

grade: stable
confinement: strict

architectures:
  - build-on: [armhf, arm64]
    run-on: [armhf, arm64]

parts:
  pwm-init:
    plugin: dump
    source: src/

apps:
  pwmjawn:
    command: bin/pwmd
    plugs:
      - pwm
